version: '3.8'

services:
  db-ditcash:
    image: mysql:8.0
    container_name: db_ditcash
    restart: always
    environment:
      MYSQL_DATABASE: ditcash_db
      MYSQL_ROOT_PASSWORD: Wildantec2026
    volumes:
      # Usamos un volumen local para tus pruebas en la computadora
      - ditcash_mysql_data_local:/var/lib/mysql
    ports:
      # Redireccionamos el puerto al 3309 para evitar el error de "Address already in use"
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pWildantec2026"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  app-ditcash:
    build: .
    container_name: app_ditcash
    restart: always
    depends_on:
      - db-ditcash 
    volumes:
      - ./app:/app/app             
      - ./components:/app/components
      - ./lib:/app/lib          
    environment:
      DATABASE_URL: "mysql://root:Wildantec2026@db-ditcash:3306/ditcash_db"
      NODE_ENV: development
      API_CONTABLE_URL: "https://grupoaraujos.cloud"
      API_CONTABLE_EMAIL: "soporte@disar-ec.com"
      API_CONTABLE_PASSWORD: "admin123"
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 256M

volumes:
  ditcash_mysql_data_local: