version: '3.8'

services:
  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: ditcash_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ditcash_db
      MYSQL_USER: ditcash_user
      MYSQL_PASSWORD: Qg;fy6?vVYV4U]Kp
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Servicio de la Aplicación NestJS
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ditcash_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # URL de conexión para Prisma (usando el nombre del servicio 'db')
      DATABASE_URL: "mysql://ditcash_user:Qg;fy6?vVYV4U]Kpo@db:3306/ditcash_db"
      PORT: 3000
    depends_on:
      - db

volumes:
  mysql_data: